version: '3.6'
services:
  simple-quiz:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '8581:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true # enable console log color
